/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tecdev;

import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class ApplyForJob extends javax.swing.JFrame {
private String userid,password,usertype;
public ApplyForJob(String u,String p,String ut){
    this();
    userid=u;
    password=p;
    usertype=ut;
    setTitle("Welcome"+userid);
    txtUserid.setText(userid);
    try{
        initialize();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e.toString());
    }
}
private void initialize()throws SQLException{
    //String sql="Select * from postjob where weightage<=(select weightage from student where userid="+userid+")";
    String sql=String.format("Select cname as company,jobid,post,weghtage,to_char(lastdate,'dd-MMM-yy')Lastdate,description from postjob where lastdate>sysdate and weightage<=(select weightage from student where userid='%s') and jobid Not in(select jobid from applied where userid='%s')",userid,userid);
ResultSet rs=DBConnection.executeQuery(sql);
jTable1.setModel(DBConnection.prepareTable(rs));
sql="select jobid,to_char(dated,'dd-MMM-yy')dated,weightage,selected,appid from applied where userid="+userid+"";
ResultSet rs2=DBConnection.executeQuery(sql);
jTable2.setModel(DBConnection.prepareTable(rs2));
boolean found=jTable1.getRowCount()>0;
btnApply.setEnabled(found);
btnSave.setEnabled(found);
btnPrint.setEnabled(found);
found=jTable2.getRowCount()>0;
btnSaveToFile.setEnabled(found);
btnPrint2.setEnabled(found);
btnCancel.setEnabled(jTable2.getRowCount()>0);



}    
/**
     * Creates new form ApplyForJob
     */
    public ApplyForJob() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnApply = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSaveToFile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnPrint2 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Userid");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 50, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("List of Available Jobs Matching your Qualification");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 62, 430, 50));
        getContentPane().add(txtUserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 210, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 570, 120));

        btnSave.setText("SAVE TO FILE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, -1, -1));

        btnApply.setText("APPLY NOW");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });
        getContentPane().add(btnApply, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, -1));

        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("List of Jobs for which you already Applied/Selected");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 242, 420, 40));

        btnSaveToFile.setText("SAVE TO FILE ");
        btnSaveToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveToFileActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveToFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 580, 120));

        btnPrint2.setText("PRINT");
        btnPrint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrint2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        btnCancel.setText("CANCEL SELECTED JOB");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, -1, -1));

        jScrollPane3.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        jScrollPane4.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        int index=jTable1.getSelectedRow();
        if(index==-1){
            JOptionPane.showMessageDialog(null,"Please Select Post To Apply!");
            
        }
        int rows[]=jTable1.getSelectedRows();
        int result=0,count=0;
        String jobid,weightage,sql="";
        try{
            for(int r:rows){
                jobid=jTable1.getValueAt(r,1).toString();
                weightage=jTable1.getValueAt(r,3).toString();
               sql=String.format("Insert into Applied Values('%s','%s',sysdate,'%s','false',appid_seq.nextval)",userid,jobid,weightage);
               result=DBConnection.executeUpdate(sql);
               if(result>0){
                   count++;
               }
               if(count>0){
                   DBConnection.commit();
                   JOptionPane.showMessageDialog(null,"You have applied for"+count+"Jobs");
                   initialize();
               }else
                   JOptionPane.showMessageDialog(null,"Failed to Apply for jobs!");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnApplyActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    int rows[]=jTable2.getSelectedRows();
        if(rows.length==0){
            JOptionPane.showMessageDialog(null,"NO Job Selected to cancel!");
            return;
        }
        String appid,sql=" ";
        int count=0,result=0;
        try{
            for(int r:rows){
                appid=jTable2.getValueAt(r,4).toString();
                sql=String.format("Delete from Applied where appid='%s'",appid);
                result=DBConnection.executeUpdate(sql);
                if(result>0){
                    count++;
                }
                if(count>0){
                    DBConnection.commit();
                    JOptionPane.showMessageDialog(null,"You have applied for"+count+"Jobs");
                }else
                    JOptionPane.showMessageDialog(null,"Failed to apply for jobs!");
             }
        
        }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.toString());
                    }
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        // TODO add your handling code here:
      int count=jTable1.getRowCount();
        if(count==0)        {
            JOptionPane.showMessageDialog(null, "Sorry. No Row Found");
            return;
        }
        StringBuffer sb=new StringBuffer(1024);
        sb.append("<html><head>Jobs</head><body>");
        sb.append("<table border=1 width=100%>");    
        for(int i=0; i<count; i++)
        {
        sb.append("<tr>");
        sb.append("<td>" + jTable1.getValueAt(i, 0)); // i-th row, 1 col
        sb.append("<td>" + jTable1.getValueAt(i, 1)); // i-th row, 2 col
        sb.append("</tr>");
        }
        sb.append("</table>");
        sb.append("</body></html>");
        try{
        FileOutputStream fos=new FileOutputStream("d:/" + userid+ ".html");
        fos.write(sb.toString().getBytes());
        fos.close();
        jTextPane1.setText(sb.toString());
         JOptionPane.showMessageDialog(null, "File Saved Successfully as d:/" + userid + ".html");
        }
        catch(Exception e)        {
            JOptionPane.showMessageDialog(null, e);
        }
    


        
          
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
      try{
            jTextPane1.print();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnSaveToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveToFileActionPerformed
        // TODO add your handling code here:
        int count=jTable2.getRowCount();
        if(count==0)        {
            JOptionPane.showMessageDialog(null, "Sorry. No Row Found");
            return;
        }
        StringBuffer sb=new StringBuffer(1024);
        sb.append("<html><head>Jobs</head><body>");
        sb.append("<table border=1 width=100%>");    
        for(int i=0; i<count; i++)
        {
        sb.append("<tr>");
        sb.append("<td>" + jTable2.getValueAt(i, 0)); // i-th row, 1 col
        sb.append("<td>" + jTable2.getValueAt(i, 1)); // i-th row, 2 col
        sb.append("</tr>");
        }
        sb.append("</table>");
        sb.append("</body></html>");
        try{
        FileOutputStream fos=new FileOutputStream("d:/" + userid+ ".html");
        fos.write(sb.toString().getBytes());
        fos.close();
        jTextPane2.setText(sb.toString());
         JOptionPane.showMessageDialog(null, "File Saved Successfully as d:/" + userid + ".html");
        }
        catch(Exception e)        {
            JOptionPane.showMessageDialog(null, e);
        }
           
    }//GEN-LAST:event_btnSaveToFileActionPerformed

    private void btnPrint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrint2ActionPerformed
        // TODO add your handling code here:
        try{
            jTextPane2.print();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_btnPrint2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplyForJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplyForJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplyForJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplyForJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplyForJob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnPrint2;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveToFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextField txtUserid;
    // End of variables declaration//GEN-END:variables
}
