/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tecdev;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class CompanyProfile extends javax.swing.JFrame {

    private String userid, password, usertype;

    public CompanyProfile(String u, String p, String ut) {
        this();
        userid = u;
        password = p;
        usertype = ut;
        setTitle("Welcome " + userid);
        txtUserid.setText(userid);

        try {
            initialize();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    private void initialize() throws SQLException {
        String sql = String.format("Select * from company where userid='%s'", userid);
        ResultSet rs = DBConnection.executeQuery(sql);
        if (rs.next()) {  //gives true when row found
            rsToText(rs);  //Display data into TextField
        } else {
            btnEdit.setText("Add");
        }
    }

    //Definition of UDF
    private void rsToText(ResultSet rs) throws SQLException {
        txtCname.setText(rs.getString("cname"));
        txtAddress.setText(rs.getString("address"));
        cmbField.setSelectedItem(rs.getString("field"));
        txtWebsite.setText(rs.getString("website"));
        dtpEstd.setDate(rs.getDate("estd"));
        txtPhone1.setText(rs.getString("phone1"));
        txtPhone2.setText(rs.getString("phone2"));
        txtEmail.setText(rs.getString("email"));
        txtCEO.setText(rs.getString("ceo"));
        txtAbout.setText(rs.getString("about"));
    }

    /**
     * Creates new form CompanyProfile
     */
    public CompanyProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserid = new javax.swing.JTextField();
        txtCname = new javax.swing.JTextField();
        dtpEstd = new org.jdesktop.swingx.JXDatePicker();
        txtCEO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        cmbField = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtWebsite = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPhone2 = new javax.swing.JTextField();
        txtPhone1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAbout = new javax.swing.JTextPane();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("USERID [READ ONLY]");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setText("COMPANY NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setText("CEO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));
        getContentPane().add(txtUserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 130, -1));
        getContentPane().add(txtCname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 140, -1));
        getContentPane().add(dtpEstd, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));
        getContentPane().add(txtCEO, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 100, -1));

        jLabel4.setText("ESTABLISHED");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        jLabel5.setText("ADDRESS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jScrollPane1.setViewportView(txtAddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 150, 50));

        jLabel6.setText("WORKING FEILD");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        cmbField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel7.setText("WEBSITE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));
        getContentPane().add(txtWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 110, -1));

        jLabel8.setText("PHONE 1");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel9.setText("PHONE 2");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, 30));

        txtPhone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhone2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPhone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 150, 20));
        getContentPane().add(txtPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 150, -1));

        jLabel10.setText("EMAIL");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 200, -1));

        jLabel11.setText("ABOUT COMPANY");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jScrollPane2.setViewportView(txtAbout);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 340, 120));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhone2ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        editable(true);

    }
    private void editable(boolean b) {
        txtCname.setEditable(b);
        txtCEO.setEditable(b);
        dtpEstd.setEditable(b);
        cmbField.setEnabled(b);
        txtAddress.setEditable(b);
        txtWebsite.setEditable(b);
        txtPhone1.setEditable(b);
        
        txtPhone2.setEditable(b);
        txtEmail.setEditable(b);
        txtAbout.setEditable(b);
        btnEdit.setEnabled(!b);   //Reverse of Other !true
        btnSave.setEnabled(b);
            // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
String cn = txtCname.getText().trim();
        String ce = txtCEO.getText().trim(); //Remove Leading/Trailing spc
        Date d = dtpEstd.getDate();
        String ad = txtAddress.getText();
        String w=txtWebsite.getText().trim();
        String f = cmbField.getSelectedItem().toString();
        String p1 = txtPhone1.getText().trim();
        String p2 = txtPhone2.getText().trim();
        String em = txtEmail.getText().trim().toLowerCase(); //OCJP Chaining
        String ab = txtAbout.getText().trim();
        if (cn.length() == 0 || ce.length() == 0 || ad.length() == 0 || w.length() == 0 || p1.length() == 0 || em.length()==0 || ab.length()==0) {
      JOptionPane.showMessageDialog(null, "Fields marked with * are Compulsory");
            return;
        }
        if (ce.matches("^[A-Z][a-z ]+$")) {
            JOptionPane.showMessageDialog(null, "Sorry!! Invalid CEO Name");
            return;
        }
        if (!p1.matches("^[1-9]{3}[0-9]{7}$")) {
            JOptionPane.showMessageDialog(null, "Sorry!! Invalid Phone Number");
            return;
        }
        if (!p2.matches("^[1-9]{3}[0-9]{7}$")) {
            JOptionPane.showMessageDialog(null, "Sorry!! Invalid Phone Number");
            return;
        }
        if (!em.matches("^(.+)@(.+)$")) {
            JOptionPane.showMessageDialog(null, "Sorry!! Invalid Email");
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yy");
        String estd = sdf.format(d);  //Format d as per sdf
        String operation = btnEdit.getText();
        String sql = "";
        if (operation.equals("Add"))
            sql = String.format("Insert into Company Values('%s' , '%s' , '%s' , '%s' ,'%s' , '%s' , '%s' , '%s' , '%s' , '%s' , '%s')", userid, cn, ad,f, w, p1, p2, em, ab, ce, estd);
        else if (operation.equals("Edit"))
            sql = String.format("Update Company set cname='%s', address='%s' , field='%s', website='%s' ,phone1='%s' , phone2='%s' ,email='%s' , about='%s', ceo='%s' where userid='%s'", cn, ad, f, w, p1,p2, em,ab,ce, userid);
            JOptionPane.showMessageDialog(null, sql);
           try {
                int result = DBConnection.executeUpdate(sql);
                if (result > 0) {
                    DBConnection.commit();
                    btnEdit.setText("Edit");
                    JOptionPane.showMessageDialog(null, "Profile Updated");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            finally {
                editable(false);
}
                    // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyProfile.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyProfile.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyProfile.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyProfile.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyProfile("lisha" ,"ahuja" , "C").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbField;
    private org.jdesktop.swingx.JXDatePicker dtpEstd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane txtAbout;
    private javax.swing.JTextPane txtAddress;
    private javax.swing.JTextField txtCEO;
    private javax.swing.JTextField txtCname;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtPhone2;
    private javax.swing.JTextField txtUserid;
    private javax.swing.JTextField txtWebsite;
    // End of variables declaration//GEN-END:variables
}
