/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tecdev;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class PostJobFrame extends javax.swing.JFrame {

    private String userid, password, usertype; //Data Member
    private String sql, operation = "";
    private ResultSet rs1, rs2;
    //private boolean foundPressed = false;
    private boolean findPressed = false;
//Add a Parameterized Constructor

    public PostJobFrame(String userid, String password, String usertype) {
        this();  //Calling DC
        this.userid = userid;
        this.password = password;
        this.usertype = usertype;
        setTitle("Welcome " + userid);
        txtUserid.setText(userid);
        try {
            initialize();  //UDF
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    } //fn
//UDF

    private void initialize() throws SQLException {
        try {
            sql = String.format("Select * from PostJob Where userid='%s' ", userid);
            rs1 = DBConnection.executeQuery(sql);
            if (rs1.last()) {
                rsToText(rs1);
            } else {
                
                emptyText(); //UDF
            }
            fetchCompanyName();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    private void fetchCompanyName() throws SQLException {
        sql = String.format("select cname from company where userid='%s' ", userid);
        ResultSet rs = DBConnection.executeQuery(sql);
        if (rs.next()) { //Fetch Row if found
            String cname = rs.getString("cname");
            txtCname.setText(cname);
            JOptionPane.showMessageDialog(null, "Cname=" + cname);
        }
    }

    private void emptyText() {
        txtJobid.setText("");
        cmbPost.setSelectedIndex(0);
        dtpDated.setDate(new Date());
        dtpLastDate.setDate(new Date());
        cmbQualification.setSelectedIndex(0);
        txtWeightage.setText("1");
        txtDescription.setText("");
    }

    private void editable(boolean b) {
        cmbPost.setEnabled(b);
        cmbQualification.setEnabled(b);
        dtpLastDate.setEnabled(b);
        dtpDated.setEnabled(b);
        txtDescription.setEditable(b);
    }

    private void enableButtons(boolean b) {
        btnAdd.setEnabled(b);
        btnEdit.setEnabled(b);
        btnSave.setEnabled(!b); //Negates
        btnDelete.setEnabled(b);
        btnSearch.setEnabled(b);
        btnFirst.setEnabled(b);
        btnPrevious.setEnabled(b);
        btnNext.setEnabled(b);
        btnLast.setEnabled(b);
        btnFind.setEnabled(b);

    }

    /**
     * Creates new form PostJobFrame
     */
    public PostJobFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUserid = new javax.swing.JTextField();
        txtCname = new javax.swing.JTextField();
        txtJobid = new javax.swing.JTextField();
        dtpDated = new org.jdesktop.swingx.JXDatePicker();
        dtpLastDate = new org.jdesktop.swingx.JXDatePicker();
        cmbPost = new javax.swing.JComboBox<>();
        cmbQualification = new javax.swing.JComboBox<>();
        txtWeightage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Weightage[read only]");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jLabel3.setText("Post");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel4.setText("Description");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel5.setText("Userid[read only]");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel6.setText("Posted On");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel7.setText("Jobid[read only]");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel8.setText("Last Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabel9.setText("Minimum Qualification");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel10.setText("Company Name[read only]");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));
        getContentPane().add(txtUserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 110, -1));
        getContentPane().add(txtCname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 130, -1));
        getContentPane().add(txtJobid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 90, -1));
        getContentPane().add(dtpDated, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));
        getContentPane().add(dtpLastDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        cmbPost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Developer", "Designer", "Testing", "CEO", "CMO", "CFO", "Executive", " " }));
        getContentPane().add(cmbPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        cmbQualification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "12", "UG", "Graduate", "PG", "Ph.D" }));
        cmbQualification.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbQualificationItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));
        getContentPane().add(txtWeightage, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 220, 70, -1));

        jScrollPane1.setViewportView(txtDescription);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 450, 70));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, -1));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, -1));

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 120, 260));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
                navigationClick(evt);
            }
        });
        jPanel2.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
                navigationClick(evt);
            }
        });
        jPanel2.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        btnPrevious.setText("Prevoius");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
                navigationClick(evt);
            }
        });
        jPanel2.add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
                navigationClick(evt);
            }
        });
        jPanel2.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel2.add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 490, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String cn = txtCname.getText();
        String j = txtJobid.getText();
        String w = txtWeightage.getText();
        String d = txtDescription.getText();
        String q = cmbQualification.getSelectedItem().toString();
        String p = cmbPost.getSelectedItem().toString();
        Date d1 = dtpDated.getDate();
        Date d2 = dtpLastDate.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yy");
        String dt = sdf.format(d1);
        String df = sdf.format(d2);
        if (d.length() == 0) {
            JOptionPane.showMessageDialog(null, "Please Type Job Description!");
            return;
        }
        if (d1.equals(d2)) {
            int choice = JOptionPane.showConfirmDialog(this, "Do you like to keep post date and last date same?", "Confirm?", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (choice == JOptionPane.NO_OPTION) {
                return;
            }

        


    }//GEN-LAST:event_btnSaveActionPerformed
    if(operation.equals ( 
        "add")){
    sql = String.format("Insert into PostJob Values('%s','%s',jobid_seq.nextval,'%s','%s','%s','%s','%s','%s')", userid, cn, dt, df, p, q, w, d);

    }

    else if(operation.equals ( 
        "edit")){
      sql = String.format("Update PostJob set lastdate='%s',qualification='%s',weightage='%s',description='%s' where userid='%s' and jobid='%s'", df, q, w, d, userid, j);
    }

    JOptionPane.showMessageDialog (

    
        null,sql);
try{
    int result = DBConnection.executeUpdate(sql);
        if (result > 0) {
            DBConnection.commit();
            initialize();
            JOptionPane.showMessageDialog(null, "Job Saved Succesfully!");

        }
    }
    catch(Exception e

    
        ){
    JOptionPane.showMessageDialog(null, "Post Job Save" + e.getMessage());
    }

    
        finally{
    editable(false);
        enableButtons(true);
        operation = "";
    }}
    private void cmbQualificationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbQualificationItemStateChanged
        int index = cmbQualification.getSelectedIndex();
        txtWeightage.setText(" " + (index + 1));
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbQualificationItemStateChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        operation = "add";
        emptyText();
        editable(true);
        enableButtons(false);
                txtJobid.setEditable(false);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        operation = "edit";
        editable(true);
        enableButtons(false);
        txtJobid.setEditable(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String jobid = txtJobid.getText().trim();
        if (jobid.length() == 0) {
            JOptionPane.showMessageDialog(null, "No Job to Delete");
            return;
        }
        int choice = JOptionPane.showConfirmDialog(this,
                "Are you Sure?", "Confirm?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        sql = String.format("Delete From PostJob Where jobid='%s' ", jobid);
        try {
            int result = DBConnection.executeUpdate(sql);
            if (result > 0) {
                DBConnection.commit();
                JOptionPane.showMessageDialog(null, "Job Deleted");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Delete " + e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String jobid = JOptionPane.showInputDialog(null, "Enter Jobid to Search");
        if (jobid == null || jobid.trim().length() == 0) //Cancel Pressed
        {
            JOptionPane.showMessageDialog(null, "Type Jobid to Search");
            return;    //Terminate Fn
        }
//Otherwise
        try {
            sql = String.format("Select * from PostJob where jobid='%s' ", jobid);
            rs2 = DBConnection.executeQuery(sql);
            boolean foundPressed = true; //We have declared this variable as boolean
            if (rs2.next()) //Gives true if row found
            {
                rsToText(rs2);    //Display data inside TextField
            } else {
                JOptionPane.showMessageDialog(null, "Sorry!! " + jobid + " Not Found");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        new SearchJobFrame(userid, password, usertype).setVisible(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLastActionPerformed

    private void navigationClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigationClick
        if (findPressed) {

            try {
                initialize();
            } catch (SQLException ex) {
                Logger.getLogger(PostJobFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            findPressed = false;
        }
        try {
            switch (evt.getActionCommand()) {
                case "First":
                    if (!rs1.first()) {
                        rs1.first();
                    }
                    break;
                case "Previous":
                    rs1.previous();
                    if (rs1.isBeforeFirst()) {
                        rs1.last();
                    }
                    break;
                case "Next":
                    rs1.next();
                    if (rs1.isAfterLast()) {
                        rs1.first();
                    }
                    break;
                case "Last":
                    if (!rs1.next()) {
                        rs1.last();
                    }
                    break;
            }
            rsToText(rs1);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_navigationClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostJobFrame("lisha" ,"ahuja" , "C").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbPost;
    private javax.swing.JComboBox<String> cmbQualification;
    private org.jdesktop.swingx.JXDatePicker dtpDated;
    private org.jdesktop.swingx.JXDatePicker dtpLastDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCname;
    private javax.swing.JTextPane txtDescription;
    private javax.swing.JTextField txtJobid;
    private javax.swing.JTextField txtUserid;
    private javax.swing.JTextField txtWeightage;
    // End of variables declaration//GEN-END:variables

    private void rsToText(ResultSet rs1) throws SQLException {
        //To change body of generated methods, choose Tools | Templates.
        txtJobid.setText(rs1.getString("jobid"));
        dtpDated.setDate(rs1.getDate("dated"));
        dtpLastDate.setDate(rs1.getDate("lastdate"));
        cmbPost.setSelectedItem(rs1.getString("post"));
        cmbQualification.setSelectedItem(rs1.getString("qualification"));
        txtWeightage.setText(rs1.getString("weightage"));
        txtDescription.setText(rs1.getString("description"));

        //txtPhone2.setText(rs.getString("phone2"));
        //txtEmail.setText(rs.getString("email"));
        //cmbLanguage.setSelectedItem(rs.getString("language"));
        //txtMobile.setText(rs.getString("ceo"));
        txtDescription.setText(rs1.getString("description"));

    }
}
