/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tecdev;

import java.io.FileOutputStream;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class SearchJobFrame extends javax.swing.JFrame {

   public String userid,password,usertype;
    public SearchJobFrame() {
        initComponents();
    }
    public SearchJobFrame(String u,String p,String ut){
        this();
        userid=u;
        password=p;
        usertype=ut;
        setTitle("Welcome"+userid);
        txtUserid.setText(userid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtUserid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSaveToFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnGo = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        cmbField = new javax.swing.JComboBox<>();
        cmbOperator = new javax.swing.JComboBox<>();
        txtValue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("USERID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));
        getContentPane().add(txtUserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 90, -1));

        jLabel3.setText("Select Field");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel4.setText("Operator");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel5.setText("Value");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        btnSaveToFile.setText("Save To File");
        btnSaveToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveToFileActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveToFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 210));

        btnGo.setText("GO");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, -1));

        cmbField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jobid", "Dated", "Lastdate", "Post", "Qualification", "Weightage", " ", " " }));
        getContentPane().add(cmbField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        cmbOperator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<=", ">=", "!=", "<", ">" }));
        getContentPane().add(cmbOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));
        getContentPane().add(txtValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
String f=cmbField.getSelectedItem().toString();
String op=cmbOperator.getSelectedItem().toString();
String v=txtValue.getText().trim().toLowerCase();
String sql=String.format("Select *from Postjob where %s %s '%s' and userid='%s'order by jobid",f,op,v,userid);
try{
    ResultSet rs=DBConnection.executeQuery(sql);
    if(rs.next()){
        rs.previous();
        jTable1.setModel(DBConnection.prepareTable(rs));
        btnSaveToFile.setEnabled(true);
        
    }
    else{
        jTable1.setModel(new DefaultTableModel());
        btnSaveToFile.setEnabled(false);
        JOptionPane.showMessageDialog(null,"NO Data Found!");
    }        
}
catch(Exception e){
    JOptionPane.showMessageDialog(null,e.toString());
}
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnSaveToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveToFileActionPerformed
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       int rows=model.getRowCount();
       
       StringBuffer sb=new StringBuffer(2*1024);
       sb.append("<html><body><table border=1>");
       sb.append("<tr>");
       sb.append("<td>Userid</td>");
       sb.append("<td>Company</td>");
        sb.append("<td>Jobid</td>");
         sb.append("<td>Post</td>");
         sb.append("<td>Qualification</td>");
        sb.append("</tr");
        String u,c,j,p,q;
        for(int i=0;i<rows;i++){
            c=model.getValueAt(i,1).toString();//cname
            j=model.getValueAt(i,2).toString();//jobid i-th row
            p=model.getValueAt(i,5).toString();  //post
            q=model.getValueAt(i,6).toString();    //qualif
            sb.append("<tr>");
            sb.append(String.format("<td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td>",userid,c,j,p,q));
            sb.append("</tr>");
            
        }
       sb.append("</table></body></html>");
       try{
           FileOutputStream fos=new FileOutputStream("C:/Users/ADMIN/Documents/"+userid+".html");
           fos.write(sb.toString().trim().getBytes());
           fos.close();
           jTextPane1.setContentType("text/html");
           jTextPane1.setText(sb.toString().trim());
           btnPrint.setEnabled(true);
           
       }
       catch(Exception e){
          JOptionPane.showMessageDialog(null,e.toString()); 
           }
               
               
               
               
               
    }//GEN-LAST:event_btnSaveToFileActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try{
            jTextPane1.print();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchJobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchJobFrame("lisha","ahuja","C").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSaveToFile;
    private javax.swing.JComboBox<String> cmbField;
    private javax.swing.JComboBox<String> cmbOperator;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txtUserid;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
