/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tecdev;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
//import static sun.management.snmp.AdaptorBootstrap.initialize;

/**
 *
 * @author ADMIN
 */
public class StudentProfile extends javax.swing.JFrame {

    /**
     * Creates new form StudentProfile
     */
    public StudentProfile() {
        initComponents();
    }
    private String userid, password, usertype;

    public StudentProfile(String u, String p, String ut) {
        this();
        userid = u;
        password = p;
        usertype = ut;
        setTitle("WELCOME " + userid);
        txtUserid.setText(userid);

        try {
            initialize();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    private void initialize() throws SQLException {
        String sql = String.format("Select * from Student where userid='%s' ", userid);
        ResultSet rs = DBConnection.executeQuery(sql);
        if (rs.next()) {
            rsToText(rs);
        } else {
            btnEdit.setText("Add");
        }

    }

    private void rsToText(ResultSet rs) throws SQLException {
        txtEnrollment.setText(rs.getString("enrollment"));
        txtName.setText(rs.getString("name"));
        cmbQualification.setSelectedItem(rs.getString("qualification"));
        txtWeightage.setText(rs.getString("weightage"));
        cmbBranch.setSelectedItem(rs.getString("branch"));
        dtpDob.setDate(rs.getDate("dob"));
        cmbGender.setSelectedItem(rs.getString("gender"));

        //txtPhone2.setText(rs.getString("phone2"));
        txtEmail.setText(rs.getString("email"));
        cmbLanguage.setSelectedItem(rs.getString("language"));
        //txtMobile.setText(rs.getString("ceo"));

        txtDescription.setText(rs.getString("description"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEnrollment = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUserid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtWeightage = new javax.swing.JTextField();
        cmbLanguage = new javax.swing.JComboBox<>();
        cmbQualification = new javax.swing.JComboBox<>();
        cmbBranch = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextPane();
        dtpDob = new org.jdesktop.swingx.JXDatePicker();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Enrollment No.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Branch:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Gender:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 50));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Birth Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Emailid:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Language:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        txtEnrollment.setEditable(false);
        txtEnrollment.setCaretColor(new java.awt.Color(255, 204, 0));
        txtEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnrollmentActionPerformed(evt);
            }
        });
        getContentPane().add(txtEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 260, -1));

        txtName.setEditable(false);
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 270, 20));

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        cmbGender.setEnabled(false);
        getContentPane().add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        txtEmail.setEditable(false);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 110, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Describe Yourself:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        txtUserid.setEditable(false);
        getContentPane().add(txtUserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 250, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Userid(read only)");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Qualification");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Weightage");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        txtWeightage.setEditable(false);
        txtWeightage.setText("1");
        getContentPane().add(txtWeightage, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 110, -1));

        cmbLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hindi", "English", "French", "Spanish" }));
        cmbLanguage.setEnabled(false);
        getContentPane().add(cmbLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        cmbQualification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "12", "UG", "Graduate", "PG", "Ph.D" }));
        cmbQualification.setEnabled(false);
        cmbQualification.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbQualificationItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        cmbBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CS", "EX", "EC", "CE", "ME", "IT", "AU", " " }));
        cmbBranch.setEnabled(false);
        getContentPane().add(cmbBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        txtDescription.setEditable(false);
        jScrollPane2.setViewportView(txtDescription);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 450, 80));

        dtpDob.setEditable(false);
        dtpDob.setEnabled(false);
        getContentPane().add(dtpDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 110, -1));

        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, -1, -1));

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Mobile");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));
        getContentPane().add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnrollmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnrollmentActionPerformed

    private void cmbQualificationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbQualificationItemStateChanged
        int index = cmbQualification.getSelectedIndex();
        txtWeightage.setText("" + (index + 1));
    }//GEN-LAST:event_cmbQualificationItemStateChanged

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        editable(true);
       // operation="edit";
    }

    private void editable(boolean b) {
        txtEnrollment.setEditable(b);
        txtName.setEditable(b);
        cmbQualification.setEnabled(b);
        cmbBranch.setEnabled(b);
        dtpDob.setEnabled(b);
        dtpDob.setEditable(b);
        cmbGender.setEnabled(b);
        txtMobile.setEditable(b);
        cmbLanguage.setEnabled(b);
        txtEmail.setEditable(b);
        txtDescription.setEditable(b);
        btnEdit.setEnabled(!b);   //Reverse of Other !true
        btnSave.setEnabled(b);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String en = txtEnrollment.getText().trim(); //Page 5
        String n = txtName.getText().trim(); //Remove Leading/Trailing spc
        String q = cmbQualification.getSelectedItem().toString();
        String w = txtWeightage.getText();
        String b = cmbBranch.getSelectedItem().toString();
        Date d = dtpDob.getDate();  //RC=>Fix Imports [ Ctrl Shift i ]
        String g = cmbGender.getSelectedItem().toString();
        String m = txtMobile.getText().trim();
        String l = cmbLanguage.getSelectedItem().toString();
        String em = txtEmail.getText().trim().toLowerCase(); //OCJP Chaining
        String desc = txtDescription.getText().trim();
        if (en.length() == 0 || n.length() == 0 || m.length() == 0 || em.length() == 0 || desc.length() == 0) {
            JOptionPane.showMessageDialog(null, "All Fields are Compulsory");
            return;
        }
        if (!en.matches("^[0-9]{4}(CS|IT|EC|CE|EX)[0-9]{2}1[0-9]{3}$")) {
            JOptionPane.showMessageDialog(null, "Sorry!! Invalid Enrollment Number");
            return;
        }
        if (!em.matches("^(.+)@(.+)$")) {
            JOptionPane.showMessageDialog(null, "Sorry!! Invalid Email");
            return;
        }
        if (!m.matches("^[1-9][0-9]{9}$")) {
            JOptionPane.showMessageDialog(null, "Sorry!! Invalid Mobile");
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yy");
        String dob = sdf.format(d);  //Format d as per sdf
        String operation = btnEdit.getText();
        String sql = "";
        if (operation.equals("Add")) {
            sql = String.format("Insert into Student Values('%s' , '%s' ,'%s' , '%s' , '%s' , '%s' , '%s' , '%s' , '%s' , '%s' ,'%s' ,'%s')", userid, en, n, q, w, b, dob, g, em, l, desc,m);
        } else if (operation.equals("Edit")) {
            sql = String.format("Update Student set name='%s',qualification='%s',weightage='%s',branch='%s',mobile='%s',email='%s',language='%s',description='%s' where userid='%s'", n, q, w, b, m, em, l, desc,userid);
        }
        //JOptionPane.showMessageDialog(null,  sql);

        try {
            int result = DBConnection.executeUpdate(sql);
            if (result > 0) {
                DBConnection.commit();
                JOptionPane.showMessageDialog(null, "Profile Updated");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to Save");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            editable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentProfile("rita", "ahuja", "S").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbBranch;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbLanguage;
    private javax.swing.JComboBox<String> cmbQualification;
    private org.jdesktop.swingx.JXDatePicker dtpDob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane txtDescription;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnrollment;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUserid;
    private javax.swing.JTextField txtWeightage;
    // End of variables declaration//GEN-END:variables
}
